#!/bin/bash
# Digital Ocean does not create a normal user by default
CreateUser()
{
	useradd loadtest_user
	mkdir /home/loadtest_user/.ssh
	chmod 0700 /home/loadtest_user/.ssh/
	cp -Rfv /root/.ssh /home/loadtest_user/
	chown -Rfv loadtest_user.loadtest_user /home/loadtest_user/.ssh
	chown -R loadtest_user:loadtest_user /home/loadtest_user/
	gpasswd -a loadtest_user sudo
	echo "loadtest_user ALL=(ALL) NOPASSWD: ALL" | (EDITOR="tee -a" visudo)
	service ssh restart
	usermod -s /bin/bash loadtest_user
}

if [ ! $(grep 1000 /etc/passwd)  ]
then
	CreateUser
fi
ENDUSER=$(id -u -n 1000)
sudo yum update -y
sudo yum install git -y
git clone https://REDACTED_TOKEN@github.com/REDACTED_GITUSERNAME/lazy-loadtest /home/$ENDUSER/lazy-loadtest
chown -R $ENDUSER.$ENDUSER /home/$ENDUSER

# Nothing will happen if you do not uncomment one of these
#sh /home/$ENDUSER/lazy-loadtest/db1000n/db1000n_setup.sh
#sh /home/$ENDUSER/lazy-loadtest/mhddos_proxy/mhddos_setup.sh
