#!/bin/bash
# Digital Ocean does not create a normal user by default
CreateUser()
{
	useradd loadtest_user
	mkdir /home/loadtest_user/.ssh
	chmod 0700 /home/loadtest_user/.ssh/
	cp -Rfv /root/.ssh /home/loadtest_user/
	chown -Rfv loadtest_user.loadtest_user /home/loadtest_user/.ssh
	chown -R loadtest_user:loadtest_user /home/loadtest_user/
	gpasswd -a loadtest_user sudo
	echo "loadtest_user ALL=(ALL) NOPASSWD: ALL" | (EDITOR="tee -a" visudo)
	service ssh restart
	usermod -s /bin/bash loadtest_user
}

if [ ! $(grep 1000 /etc/passwd)  ]
then
	CreateUser
fi
# Set environment variables
ENDUSER=$(id -u -n 1000)
GITPATH=/home/$ENDUSER/lazy-loadtest
# Install git and clone repo
sudo yum update -y
sudo yum install git -y
git clone https://github.com/lazyloadtest/lazy-loadtest.git $GITPATH

# Pull in VPN password and config files here

chown -R $ENDUSER.$ENDUSER /home/$ENDUSER
sh $GITPATH/common/docker_setup.sh

# Nothing will happen if you do not uncomment one of these
#sh $GITPATH/db1000n/db1000n_setup.sh
#sh $GITPATH/mhddos_proxy/mhddos_setup.sh
#sh $GITPATH/disbalancer/disbalancer_setup.sh
