  db1000n:
    image: ghcr.io/arriven/db1000n:latest
    container_name: db1000n
    restart: unless-stopped
    depends_on:
      openvpn-client:
        condition: service_healthy
    network_mode: service:openvpn-client
    labels:
        autoheal: "true"
    environment:
      STRICT_COUNTRY_CHECK: "false"
      COUNTRY_LIST: "Country"
